palette: [ [ 200, 60, 100 ],
           [ 100, 50, 250 ],
           [ 75, 200, 50 ],
           [ 102, 51, 229 ],
           [ 255, 127, 0 ],
           [ 255, 255, 0 ],
           [ 127, 0, 255 ],
           [ 0, 127, 255 ]]

potential_close:
  - [0.000001, 0.000001, 0.000001, 0.000001]
  - [0.000001, 0.000001, 0.000001, 0.000001]
  - [0.000001, 0.000001, 0.000001, 0.000001]
  - [0.000001, 0.000001, 0.000001, 0.000001]

potential_trough:
  - [1000000, 2500000, 1000000, 1000000]
  - [2500000, 1000000, 1000000, 1000000]
  - [1000000, 1000000, 1000000, 4000000]
  - [1000000, 1000000, 4000000, 1000000]

potential_peak:
  - [ 1, 0.25, 0.002, 0.002]
  - [0.25,  1,  0.01, 0.002]
  - [0.002,  0.01,  0.01, 0.01]
  - [0.002, 0.002, 0.01,  0.01]

potential_far:
  - [0.02, 0.02, 0.02, 0.04]
  - [0.02, 0.08, 0.04, 0.08]
  - [0.02, 0.04, 0.08, 0.08]
  - [0.04, 0.08, 0.08, 0.04]

masses: [1, 1, 1, 1]
dt: 0.01
max_init_speed: 0
speed_limit: 1000000
#n_particles_per_type: [7225, 7225]
#n_particles_per_type: [2500, 2500]
#n_particles_per_type: [2450, 2450, 2450, 2450]
#n_particles_per_type: [3200, 3200, 3200, 3200]
#n_particles_per_type: [3698, 3698, 3698, 3698]
n_particles_per_type: [4050, 4050, 4050, 4050]
#n_particles_per_type: [6050, 6050, 6050, 6050]
#n_particles_per_type: [1000, 1000]
#n_particles_per_type: [100, 100, 100, 100]
seed: 24
num_steps: 1000

# "core" or "uniform"
initialization_mode: "uniform"
core_size: 0.125

stochastic: False
n_transfers_per_step: 4000
transfer_intensity: 0.004

log_energy: False