# bright green, dark green, indigo, pink-magenta, orange, bright yellow, blue-magenta, blue-cyan
palette: [ [ 75, 200, 50 ],
           [ 0, 175, 127 ],
           [ 102, 51, 229 ],
           [ 204, 51, 127 ],
           [ 255, 127, 0 ],
           [ 255, 255, 0 ],
           [ 127, 0, 255 ],
           [ 0, 127, 255 ]]

potential_close:
  - [0.005, 0.01, 0.005, 0.01]
  - [ 0.01, 0.01,  0.01, 0.02]
  - [0.005, 0.01, 0.005, 0.02]
  - [ 0.01, 0.02,  0.02, 0.01]

potential_trough:
  - [ -0.02, -0.005, -0.005, -0.005]
  - [-0.005,  -0.02,  -0.02,  -0.02]
  - [-0.005,  -0.02,  -0.01, -0.01]
  - [-0.005,  -0.02, -0.01,  -0.01]

potential_peak:
  - [ 0.02, 0.005, 0.005, 0.005]
  - [0.005,  0.02,  0.01, 0.005]
  - [0.005,  0.01,  0.01, 0.01]
  - [0.005, 0.005, 0.01,  0.01]

potential_far:
  - [0.0286, 0.0143, 0.02, 0.04]
  - [0.0143, 0.0286, 0.04, 0.08]
  - [0.02, 0.04, 0.08, 0.08]
  - [0.04, 0.08, 0.08, 0.04]

masses: [1, 1, 1, 1]
dt: 0.01
max_init_speed: 0
speed_limit: 1000000000
n_particles_per_type: [2450, 2450, 2450, 2450]
#n_particles_per_type: [100, 100, 100, 100]
seed: 24
num_steps: 1000

# "core" or "uniform"
initialization_mode: "core"
core_size: 0.125

stochastic: True
n_transfers_per_step: 4000
transfer_intensity: 0.0003

sparse: False
neighborhood_search_depth: 2